package org.jbpm.smoketest.invoice;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class InvoiceLine  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double price;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String product;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer quantity;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Double total;

    public InvoiceLine() {
    }

    public InvoiceLine(java.lang.String product, java.lang.Integer quantity, java.lang.Double price, java.lang.Double total) {
        this.product = product;
        this.quantity = quantity;
        this.price = price;
        this.total = total;
    }


    
    public java.lang.Double getPrice() {
        return this.price;
    }

    public void setPrice(  java.lang.Double price ) {
        this.price = price;
    }
    
    public java.lang.String getProduct() {
        return this.product;
    }

    public void setProduct(  java.lang.String product ) {
        this.product = product;
    }
    
    public java.lang.Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(  java.lang.Integer quantity ) {
        this.quantity = quantity;
    }
    
    public java.lang.Double getTotal() {
        return this.total;
    }

    public void setTotal(  java.lang.Double total ) {
        this.total = total;
    }
}